<?php

return [
    'icons' => [
        'dayoff' => 'lock-time',
        'collect' => 'clipboard',
        'collect-task' => 'cash',
        'collect-task-ppn' => 'sale-percent',
        'collect-idy-ppn' => 'cash-register',
        'driver' => 'truck',
        'sales' => 'receipt',
        'technician' => 'hammer',
        'capture' => 'camera',
        'pegawai' => 'address-book',
        'jabatan' => 'briefcase',
        'golongan' => 'users-group',
        'division' => 'object-column',
        'placement' => 'landmark',
        'users' => 'profile-card',
        'roles' => 'badge-check',
        'permissions' => 'adjustment',
        'log' => 'window',
        'announcement' => 'bullhorn',
        'backup' => 'filezip',
        'angle-right' => 'angle-right',
        'arrow-right' => 'arrow-right',
        'arrow-left' => 'arrow-left',
        'book-open' => 'book-open',
        'event' => 'gift-box',
        'invoice' => 'file-invoice',
    ],
    'links' => [
        [
            'permission' => 'dayoff-list',
            'link' => 'dayoff.index',
            'check' => 'dayoff.*',
            'label' => 'Pengajuan Cuti',
            'icon' => 'dayoff',
        ],
        [
            'permission' => 'collect-task-list',
            'link' => 'collect-task.index',
            'check' => 'collect-task.*',
            'label' => 'IDC Non (SR)',
            'icon' => 'collect-task',
        ],
        [
            'permission' => 'collect-task-ppn-list',
            'link' => 'collect-task-ppn.index',
            'check' => 'collect-task-ppn.*',
            'label' => 'IDC PPN (FP)',
            'icon' => 'collect-task-ppn',
        ],
        [
            'permission' => 'collect-idy-ppn-list',
            'link' => 'collect-idy-ppn.index',
            'check' => 'collect-idy-ppn.*',
            'label' => 'IDY PPN (FP)',
            'icon' => 'collect-idy-ppn',
        ],
        [
            'permission' => 'invoice-list',
            'link' => 'invoice.medan.index',
            'check' => 'invoice.medan.*',
            'label' => 'Laporan Invoice Medan',
            'icon' => 'invoice',
        ],
        [
            'permission' => 'invoice-list-pku',
            'link' => 'invoice.pku.index',
            'check' => 'invoice.pku.*',
            'label' => 'Laporan Invoice PKU',
            'icon' => 'invoice',
        ],
        [
            'permission' => 'invoice-list-jkt',
            'link' => 'invoice.jkt.index',
            'check' => 'invoice.jkt.*',
            'label' => 'Laporan Invoice JKT',
            'icon' => 'invoice',
        ],
        [
            'permission' => 'driver-list',
            'link' => 'driver.index',
            'check' => 'driver.index',
            'label' => 'Laporan Driver',
            'icon' => 'driver',
        ],
        [
            'permission' => 'driver-approve',
            'link' => 'driver.assign.add',
            'check' => 'driver.assign.add',
            'label' => 'Assign Laporan Driver',
            'icon' => 'driver',
        ],
        [
            'permission' => 'collect-list',
            'link' => 'collect.index',
            'check' => 'collect.*',
            'label' => 'Laporan Kolektor',
            'icon' => 'collect',
        ],
        [
            'permission' => 'sales-list',
            'link' => 'sales.index',
            'check' => 'sales.*',
            'label' => 'Laporan Sales',
            'icon' => 'sales',
        ],
        [
            'permission' => 'technician-list',
            'link' => 'technician.index',
            'check' => 'technician.*',
            'label' => 'Laporan Teknisi',
            'icon' => 'technician',
        ],
        // spk
        [
            'permission' => 'spk-list',
            'link' => 'spk.index',
            'check' => 'spk.*',
            'label' => 'Data SPK',
            'icon' => 'invoice',
        ],
        [
            'permission' => 'purchasing-request-list',
            'link' => 'purchasing-request.index',
            'check' => 'purchasing-request.*',
            'label' => 'Purchasing Request',
            'icon' => 'invoice',
        ],
        [
            'permission' => 'produksi-list',
            'link' => 'production.index',
            'check' => 'production.*',
            'label' => 'Manajemen Produksi',
            'icon' => 'invoice',
        ],
        [
            'permission' => 'spk-update-informasi-pengiriman',
            'link' => 'delivery.index',
            'check' => 'delivery.*',
            'label' => 'Pengiriman',
            'icon' => 'driver',
        ],
        [
            'permission' => [
                'spk-update-no-tagihan-idcppn',
                'spk-update-no-tagihan-idcnonppn',
                'spk-update-no-tagihan-idyppn',
            ],
            'link' => 'billing.index',
            'check' => 'billing.*',
            'label' => 'Penagihan',
            'icon' => 'invoice',
        ],
        [
            'permission' => 'spk-update-informasi-pengiriman',
            'link' => 'daily-report.index',
            'check' => 'daily-report.*',
            'label' => 'Laporan Harian',
            'icon' => 'driver',
        ],
        // end spk
        [
            'permission' => 'driver-approve',
            'link' => 'routes.driver',
            'check' => 'routes.driver',
            'label' => 'Rute Driver',
            'icon' => 'angle-right',
        ],
        [
            'permission' => 'collect-approve',
            'link' => 'routes.collector',
            'check' => 'routes.collector',
            'label' => 'Rute Kolektor',
            'icon' => 'angle-right',
        ],
        [
            'permission' => 'sales-approve',
            'link' => 'routes.sales',
            'check' => 'routes.sales',
            'label' => 'Rute Sales',
            'icon' => 'angle-right',
        ],
        [
            'permission' => 'capture',
            'link' => 'capture.index',
            'check' => 'capture.index',
            'label' => 'Absensi',
            'icon' => 'capture',
        ],
        [
            'permission' => 'capture-route',
            'link' => 'capture.route',
            'check' => 'capture.route',
            'label' => 'Absensi Rute',
            'icon' => 'capture',
        ],
        [
            'permission' => 'technician-list',
            'link' => 'points.index',
            'check' => 'points.*',
            'label' => 'Poin Masuk',
            'icon' => 'arrow-right',
        ],
        [
            'permission' => 'point-redeem',
            'link' => 'technicianpoints.transactions',
            'check' => 'technicianpoints.*',
            'label' => 'Poin Keluar',
            'icon' => 'arrow-left',
        ],
        [
            'permission' => 'pegawai-list',
            'link' => 'pegawai.index',
            'check' => 'pegawai.*',
            'label' => 'Pegawai',
            'icon' => 'pegawai',
        ],
        [
            'permission' => 'jabatan-list',
            'link' => 'jabatan.index',
            'check' => 'jabatan.*',
            'label' => 'Jabatan',
            'icon' => 'jabatan',
        ],
        [
            'permission' => 'golongan-list',
            'link' => 'golongan.index',
            'check' => 'golongan.*',
            'label' => 'Golongan',
            'icon' => 'golongan',
        ],
        [
            'permission' => 'divisi-list',
            'link' => 'division.index',
            'check' => 'division.*',
            'label' => 'Divisi',
            'icon' => 'division',
        ],
        [
            'permission' => 'placement-list',
            'link' => 'placement.index',
            'check' => 'placement.*',
            'label' => 'Lokasi',
            'icon' => 'placement',
        ],
        [
            'permission' => 'users-list',
            'link' => 'users.index',
            'check' => 'users.*',
            'label' => 'Users',
            'icon' => 'users',
        ],
        [
            'permission' => 'roles-list',
            'link' => 'roles.index',
            'check' => 'roles.*',
            'label' => 'Roles',
            'icon' => 'roles',
        ],
        [
            'permission' => 'permissions-list',
            'link' => 'permissions.index',
            'check' => 'permissions.*',
            'label' => 'Hak Akses',
            'icon' => 'permissions',
        ],
        [
            'permission' => 'log-list',
            'link' => 'log.index',
            'check' => 'log.*',
            'label' => 'Log',
            'icon' => 'log',
        ],
        [
            'permission' => 'announcement-list',
            'link' => 'announcement.index',
            'check' => 'announcement.*',
            'label' => 'Pusat Notifikasi',
            'icon' => 'announcement',
        ],
        [
            'permission' => 'event-manage',
            'link' => 'event.index',
            'check' => 'event.*',
            'label' => 'Event',
            'icon' => 'event',
        ],
        [
            'permission' => 'backup-list',
            'link' => 'backup.index',
            'check' => 'backup.*',
            'label' => 'Manage Backup',
            'icon' => 'backup',
        ],
        [
            'permission' => 'technician-approve',
            'link' => 'map.distribution',
            'check' => 'map.*',
            'label' => 'Peta Penyebaran',
            'icon' => 'book-open',
        ],
    ],
];
